In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
df = pd.read_csv('../data/processed/granger.csv')

In [18]:
df[df['source name']=='LP']

,source name,source #neur,target name,target #neur,Granger score,corrected p,eid
84,LP,27,CP,47,0.025535,0.014241,b39752db-abdb-47ab-ae78-e8608bbf50ed
150,LP,61,SSp-tr,64,0.020445,0.014241,ebce500b-c530-47de-8cb1-963c552703ea
214,LP,69,VISa,29,0.017391,0.014241,56b57c38-2699-4091-90a8-aba35103155e
229,LP,91,PO,150,0.016971,0.014241,0802ced5-33a3-405e-8336-b65ebc5cb07c
332,LP,39,PO,25,0.014505,0.014241,ff96bfe1-d925-4553-94b5-bf8297adf259
...,...,...,...,...,...,...,...
6841,LP,12,POL,24,0.000403,0.014241,8a3a0197-b40a-449f-be55-c00b23253bbf
6860,LP,16,POL,13,0.000395,1.000000,0c828385-6dd6-4842-a702-c5075f5f5e81
6880,LP,25,Eth,12,0.000381,0.014241,dda5fc59-f09a-4256-9fb5-66c67667a466
6917,LP,39,MRN,26,0.000356,0.014241,e2b845a1-e313-4a08-bc61-a5f662ed295e
6920,LP,25,CA1,15,0.000349,0.014241,dda5fc59-f09a-4256-9fb5-66c67667a466

In [20]:
names, counts = np.unique(df['source name'], return_counts=True)

In [25]:
sortidx = np.argsort(counts)[::-1]

In [43]:
names[sortidx][0:20]

array(['MRN', 'CA1', 'LP', 'SCm', 'CP', 'PO', 'APN', 'DG', 'VPM', 'VISa',
       'MOs', 'LSr', 'PAG', 'IRN', 'VISp', 'CA3', 'IP', 'CUL4 5', 'MV',
       'ACAd'], dtype=object)

In [44]:
counts[sortidx][0:20]

array([258, 246, 217, 181, 171, 170, 155, 147, 134, 131, 130, 109, 106,
       106, 101,  93,  93,  89,  83,  72], dtype=int64)

,source name,source #neur,target name,target #neur,Granger score,corrected p,eid
0,IRN,23,PARN,34,0.113965,0.014241,c4432264-e1ae-446f-8a07-6280abade813
1,RSPv,49,RSPd,18,0.094231,1.000000,537677fe-1e24-4755-948c-fa4a4e8ecce5
2,RSPv,23,RSPd,16,0.089403,1.000000,f819d499-8bf7-4da0-a431-15377a8319d5
3,CA1,82,DG,90,0.085853,0.014241,fcd49e34-f07b-441c-b2ac-cb8c462ec5ac
4,LSr,159,PS,26,0.081340,0.014241,4ecb5d24-f5cc-402c-be28-9d0f7cb14b3a
...,...,...,...,...,...,...,...
6981,SUB,11,MRN,15,0.000250,0.014241,68775ca0-b056-48d5-b6ae-a4c2a76ae48f
6982,VISl,21,ENTl,17,0.000244,0.014241,5d6aa933-4b00-4e99-ae2d-5003657592e9
6983,ENTl,17,IC,33,0.000237,1.000000,5d6aa933-4b00-4e99-ae2d-5003657592e9
6984,VISl,21,CENT2,52,0.000230,1.000000,5d6aa933-4b00-4e99-ae2d-5003657592e9
6985,HATA,20,PYR,11,0.000168,0.014241,1928bf72-2002-46a6-8930-728420402e01

In [55]:
df['average'] = df[['source #neur', 'target #neur']].mean(axis=1)

In [56]:
df.sort_values(by='average')

,source name,source #neur,target name,target #neur,Granger score,corrected p,eid,average
6036,LP,11,DG,11,0.000707,0.014241,c99d53e6-c317-4c53-99ba-070b26673ac4,11.0
1394,PYR,11,SPVI,11,0.006256,0.014241,1928bf72-2002-46a6-8930-728420402e01,11.0
3580,SCs,11,VISp,11,0.002241,0.014241,f56194bc-8215-4ae8-bc6a-89781ad8e050,11.0
1489,CUN,11,IC,11,0.005893,0.014241,c3d9b6fb-7fa9-4413-a364-92a54df0fc5d,11.0
1707,SCs,11,CA3,11,0.005191,0.014241,f56194bc-8215-4ae8-bc6a-89781ad8e050,11.0
...,...,...,...,...,...,...,...,...
1914,MV,37,CUL4 5,219,0.004643,0.014241,f10efe41-0dc0-44d0-8f26-5ff68dca23e9,128.0
3939,NOD,51,CUL4 5,219,0.001925,0.014241,f10efe41-0dc0-44d0-8f26-5ff68dca23e9,135.0
5651,CUL4 5,219,NOD,51,0.000857,0.014241,f10efe41-0dc0-44d0-8f26-5ff68dca23e9,135.0
1781,LSr,159,MOB,125,0.004977,0.131040,4ecb5d24-f5cc-402c-be28-9d0f7cb14b3a,142.0
2986,MOB,125,LSr,159,0.002903,0.014241,4ecb5d24-f5cc-402c-be28-9d0f7cb14b3a,142.0

In [60]:
df[(df['source name']=='CA1') &  (df['target name']=='DG')]

,source name,source #neur,target name,target #neur,Granger score,corrected p,eid,average
3,CA1,82,DG,90,0.085853,0.014241,fcd49e34-f07b-441c-b2ac-cb8c462ec5ac,86.0
22,CA1,17,DG,17,0.037822,1.000000,dc962048-89bb-4e6a-96a9-b062a2be1426,17.0
42,CA1,29,DG,32,0.032532,0.014241,f56194bc-8215-4ae8-bc6a-89781ad8e050,30.5
114,CA1,32,DG,32,0.022631,0.014241,2bdf206a-820f-402f-920a-9e86cd5388a4,32.0
158,CA1,11,DG,14,0.019847,0.014241,15b69921-d471-4ded-8814-2adad954bcd8,12.5
233,CA1,13,DG,12,0.016884,0.014241,8928f98a-b411-497e-aa4b-aa752434686d,12.5
263,CA1,27,DG,24,0.016027,1.000000,510b1a50-825d-44ce-86f6-9678f5396e02,25.5
282,CA1,31,DG,18,0.015618,0.014241,caa5dddc-9290-4e27-9f5e-575ba3598614,24.5
393,CA1,28,DG,16,0.013458,0.014241,e2b845a1-e313-4a08-bc61-a5f662ed295e,22.0
814,CA1,27,DG,19,0.009135,1.000000,b52182e7-39f6-4914-9717-136db589706e,23.0
927,CA1,15,DG,14,0.008454,0.014241,dda5fc59-f09a-4256-9fb5-66c67667a466,14.5
950,CA1,15,DG,21,0.008362,0.014241,ee40aece-cffd-4edb-a4b6-155f158c666a,18.0
968,CA1,23,DG,16,0.008266,0.014241,ecb5520d-1358-434c-95ec-93687ecd1396,19.5
2941,CA1,39,DG,20,0.002956,1.000000,446f4724-1690-49f9-819a-2bd8e2ea88ce,29.5
4788,CA1,11,DG,31,0.001316,0.014241,f9860a11-24d3-452e-ab95-39e199f20a93,21.0
5079,CA1,14,DG,49,0.001159,0.014241,0cf6d255-8f2f-463e-84fb-c54bacb79f51,31.5
5189,CA1,17,DG,13,0.001092,0.014241,e8b4fda3-7fe4-4706-8ec2-91036cfee6bd,15.0
6677,CA1,15,DG,33,0.000470,1.000000,37e96d0b-5b4b-4c6e-9b29-7edbdc94bbd0,24.0

In [ ]:
#NOTE: Find out regions we want from the BWM and the prior paper